### ISSUE TITLE
NeoJSON loads from master and not from gs_master ?

### ISSUE THREAD

**Issue by MFeldtmann** [GsDevKit/zinc#68]
Why is NeoJSON referenced via "github://GsDevKit/NeoJSON:master/repository" and not via the published "github://GsDevKit/NeoJSON:gs_master/repository" ? All the newly Unicode stuff is then missing ...

Marten

**Comment by dalehenrich** [comment]
@MFeldtmann that change is wrapped up in PR #66 ... and PR #66 is waiting for a me to finish up with the the [gem server work](https://github.com/GsDevKit/gsApplicationTools/pull/11)
