### ISSUE TITLE
Can not load ZincHTTPComponents-REST any more ???? Configuration error ?

### ISSUE THREAD

**Issue by feldti** [GsDevKit/zinc#84]
I get loading error while executing the code below.

Is this a typo in the github repository (https://github.com/GsDevKit/zinc/blob/gs_master/repository/BaselineOfZincHTTPComponents.package/BaselineOfZincHTTPComponents.class/instance/baseline..st) ?

github://GsDevKit/zodiac:gs_master/repository

vs.

github://GsDevKit/Zodiac:gs_master/repository

GsDeployer deploy: [
Metacello new
baseline: 'ZincHTTPComponents';
repository: 'github://GsDevKit/zinc:gs_master/repository';
onLock: [:ex | ex honor ];
load: 'REST' ].
%
--transcript--'Fetched -> BaselineOfZincHTTPComponents-dkh.27 --- github://GsDevKit/zinc:gs_master/repository [811da98:gs_master] --- github://GsDevKit/zinc:gs_master/repository'
--transcript--'Loaded -> BaselineOfZincHTTPComponents-dkh.27 --- github://GsDevKit/zinc:gs_master/repository [811da98:gs_master] --- github://GsDevKit/zinc:gs_master/repository'
--transcript--'Loading baseline of BaselineOfZincHTTPComponents...'
ERROR 2710 , a MetacelloConflictingProjectError occurred (error 2710), , Load Conflict between existing BaselineOfZodiac [baseline] from github://GsDevKit/zodiac:gs_master/repository and BaselineOfZodiac [baseline] from github://GsDevKit/Zodiac:gs_master/repository (MetacelloConflictingProjectError)

**Comment by dalehenrich** [comment]
See [this post](http://forum.world.st/Load-conflict-ZincHTTPComponents-tp5071985p5072298.html) for a more detailed discussion ...
